# Generated by Django 4.2.2 on 2023-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_patient",
        ),
        migrations.AddField(
            model_name="user",
            name="is_reception",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has permissions to access reception dashboard.",
                verbose_name="Reception",
            ),
        ),
    ]
