# Generated by Django 4.2.2 on 2023-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_doctor_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="avatar",
            field=models.ImageField(
                default="default/user_cwydgg.jpg", upload_to="Doctor Image"
            ),
        ),
    ]
