# Generated by Django 4.2.2 on 2023-06-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
