# Generated by Django 4.2.2 on 2023-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_doctor_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="avatar",
            field=models.ImageField(
                default="DoctorImage/default/user_cwydgg.jpg", upload_to="DoctorImage"
            ),
        ),
    ]
