# Generated by Django 4.2.2 on 2023-06-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="doctor",
        ),
        migrations.AddField(
            model_name="doctor",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.department",
            ),
        ),
    ]
