# Generated by Django 4.2.2 on 2023-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_department_doctor_doctor_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
