# Generated by Django 4.2.2 on 2023-06-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_doctor_avatar_alter_patient_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="avatar",
            field=models.ImageField(
                default="media/default/user.jpg", upload_to="DoctorImage"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="avatar",
            field=models.ImageField(
                default="media/default/user.jpg", upload_to="PatientImage"
            ),
        ),
    ]
