# Generated by Django 4.2.2 on 2023-06-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_department_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
